service: email-schedule-nestjs

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    APP_PORT: ${env:APP_PORT}
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}
    EMAIL_FROM: ${env:EMAIL_FROM}
    EMAIL_SUBJECT: ${env:EMAIL_SUBJECT}
    NOTION_TOKEN: ${env:NOTION_TOKEN}
    NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}

functions:
  emails-schedule:
    handler: dist/serverless.handler
    events:
      - schedule: cron(0 6 * * ? *)
